### PR TITLE
fix move images from dev 2 dest

### PR DESCRIPTION
**Pull request by MaximusFT**
)) minor fixing

### CODE REVIEW

**Comment by MaximusFT** [comment]
@wwwebman Sorry, for more than one commit.
I want pull only:
"fix move images from dev 2 dest"
Becouse imagesi in dev not move in dest folder.

**Comment by wwwebman** [comment]
Oh I see... @MaximusFT ... great, thanks!
The problem is: if I merge  all your changes will be added. I don't want them all.
I recommend you to checkout on branch which will be up to date with default master branch then: 
commit > send bugfix via pull request.

**If you don't want do one more request I will make update soon.** 

For the next time: create issue > let's discuss > create branch > commit > pull request

**Comment by MaximusFT** [comment]
Ok, in next time, I'll be carreful.

**Comment by wwwebman** [comment]
@MaximusFT ,  could you please, describe what exactly don't work for you, which OS an so on ('fix move images from dev 2 dest'). Generally i need more details. Please, open issue for this. 

If you still working with starter, maybe you have any other propositions or something to make this tool better (open one more issue if yes).  Thank you!

I have added you to chat. You can send any of you feedback there:
https://gitter.im/gulp-webpack-starter/Lobby

**Pull request closed without merging**
